AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function - uploaderHandler
  UploadHandler:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: uploadHandler/
      Handler: dist/index.handler # TODO
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Endpoint for uploading image and videos
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref JobTable
        - S3CrudPolicy:
            BucketName: !Ref SrcBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          JOB_TABLE: !Ref JobTable
          SRC_BUCKET: !Ref SrcBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /job
            Method: POST

  PostProcessHandler:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: postProcessHandler/
      Handler: dist/index.handler # TODO 
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Endpoint for post processing results
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref JobTable
        - S3CrudPolicy:
            BucketName: !Ref SrcBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          JOB_TABLE: !Ref JobTable
          SRC_BUCKET: !Ref SrcBucket
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PostProcessHandlerQueue.Arn

    
  # This is an SQS queue with all default configuration properties. To learn more about the available options, see
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
  PostProcessHandlerQueue:
    Properties:
      ReceiveMessageWaitTimeSeconds: 5
      VisibilityTimeout: 1000
    Type: AWS::SQS::Queue


  # DynamoDB table to store job information
  JobTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  
  # S3 bucket 
  SrcBucket:
    Type: AWS::S3::Bucket

    
Outputs:
  UploadHandlerEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UploadHandlerFunction:
    Value: !Ref UploadHandler
  PostProcessHandlerFuntion:
    Value: !Ref PostProcessHandler
  # SrcBucket:
  #   Value: !Ref SrcBucket
  # JobTableName:
  #   Value: !Ref JobTable
  # PostProcessHandlerQueue:
  #   Value
  

