POST https://knfxd86hz7.execute-api.ap-southeast-2.amazonaws.com/Prod/job HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "time2": "{{$localDatetime iso8601}}"
}

###

POST http://127.0.0.1:3000/job HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "time2": "{{$localDatetime iso8601}}"
}


###

GET https://k10ddj41h3.execute-api.ap-southeast-2.amazonaws.com/test/uploads3 HTTP/1.1
content-type: application/json

{"email": "sample_email@gmail.com","jobID": "Wed, 21 Oct 2015 18:27:50 GMT"}



###
POST https://knfxd86hz7.execute-api.ap-southeast-2.amazonaws.com/Prod/job HTTP/1.1
content-type: application/json

{"email": "sample_email@gmail.com","fileName":"test_instagram.mp4"}


### 
POST https://knfxd86hz7.execute-api.ap-southeast-2.amazonaws.com/Prod/job HTTP/1.1
content-type: application/json

{"email": "sample_email@gmail.com","fileName":"test.jpeg","jobID":"e59d4681-3207-467c-a477-cc934f154e2c"}

### 

POST https://knfxd86hz7.execute-api.ap-southeast-2.amazonaws.com/Prod/job HTTP/1.1
content-type: application/json

{"uploadDone": "true", "jobID":"e59d4681-3207-467c-a477-cc934f154e2c"}

