
@root_url = https://knfxd86hz7.execute-api.ap-southeast-2.amazonaws.com/Prod/
//@root_url = https://2fr7fj3ota.execute-api.ap-southeast-2.amazonaws.com/Prod/job/


### request upload 
POST {{root_url}}/job/upload-request HTTP/1.1
content-type: application/json

{"email": "beining0026@gmail.com","fileNames":["test_instagram.mp4","test.jpg"]}


### send verification code
POST {{root_url}}/job/verify-code HTTP/1.1
content-type: application/json

{"jobID": "98a28539-1346-49d6-96af-496850deb006","verificationCode":"276931"}

### update email
POST {{root_url}}/job/update-email HTTP/1.1
content-type: application/json

{"jobID": "dca52485-50a2-4817-bd14-ece6ed6648a5","email":"beining0026@gmail.com"}

### resend code
POST {{root_url}}/job/resend-code HTTP/1.1
content-type: application/json

{"jobID": "08a4e002-37b0-4a94-89ae-cd0551099dd0"}


### upload completion
POST {{root_url}}/job/upload-done HTTP/1.1
content-type: application/json

{"jobID2":"98a28539-1346-49d6-96af-496850deb006"}

### update email

POST {{root_url}}/job/update-email HTTP/1.1
content-type: application/json

{"jobID": "1c2209d5-1ca6-42c7-a800-0eb80ac9ed84","email":"bche0026@studnet.monash.edu"}


