name: sam-pipeline-develop

on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      # sam build 
      - run: sam build --use-container 
      # sam deploy
      - run: >-
          sam deploy 
          --no-confirm-changeset 
          --no-fail-on-empty-changeset 
          --stack-name visual-testing 
          --s3-bucket visual-testing-cd 
          --capabilities CAPABILITY_IAM 
          --region ap-southeast-2 
